#!/bin/zsh

__prompt_git_color()
{
    if git status --porcelain 2>/dev/null | grep -q .; then
        echo "%F{9}"
    else
        # If `git status --porcelain' returned 0
        if [ "${pipestatus%% *}" = "0" ]; then
            echo "%F{226}"
        fi
    fi
}

__prompt_pwd_color()
{
    if [ -n "${SSH_CONNECTION}" ]; then
        echo "%F{45}"
    else
        echo "%F{2}"
    fi
}

precmd()
{
    PROMPT="%(!.%F{11}.%F{14})%n%F{63}@%m$(__prompt_git_color)->%f "
    RPROMPT="$(__prompt_pwd_color)[%~]%f %(?.%F{2}.%F{9})[%?]"
}

